apiVersion: v1
kind: Service
metadata:
  name: driver-service
  namespace: lastmile
spec:
  selector:
    app: driver-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP