apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trip-service-ingress
  namespace: lastmile
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: lastmile.local
    http:
      paths:
      - path: /api/trip(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: trip-service
            port:
              number: 8000