apiVersion: v1
kind: ConfigMap
metadata:
  name: lastmile-config
  namespace: lastmile
data:
  allowed_origins: "http://lastmile.local"
  user_service_url: "http://lastmile.local/api/user"
  driver_service_url: "http://lastmile.local/api/driver"