apiVersion: v1
kind: Service
metadata:
  name: station-service
  namespace: lastmile
spec:
  selector:
    app: station-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP